const EmployeeList = [
  {
    id: "001",
    firstname: "Anderson",
    lastname: "Kristin",
    age: 31,
    gender: "Male",
    phoneNumber: "(559) 738-5676",
    position: "Senior",
    department: "Fashion Designer",
    salary: 50000,
  },
  {
    id: "002",
    firstname: "Clark",
    lastname: "Cole",
    age: 22,
    gender: "Female",
    phoneNumber: "(209) 723-2920",
    position: "Middle",
    department: "Fashion Designer",
    salary: 29000,
  },
  {
    id: "003",
    firstname: "Guajardo",
    lastname: "Anita",
    age: 35,
    gender: "Female",
    phoneNumber: "(559) 738-2263",
    position: "Manager",
    department: "Sales Administrator",
    salary: 42000,
  },
  {
    id: "004",
    firstname: "Ray",
    lastname: "Lori",
    age: 32,
    gender: "Female",
    phoneNumber: "(209) 723-2945",
    position: "Assistant Manager",
    department: "Sales Administrator",
    salary: 35000,
  },
  {
    id: "005",
    firstname: "Williams",
    lastname: "Taylor",
    age: 46,
    gender: "Male",
    phoneNumber: "(559) 276-4304",
    position: "Executive",
    department: "Accounting",
    salary: 80000,
  },
  {
    id: "006",
    firstname: "Roy",
    lastname: "Lanler",
    age: 33,
    gender: "Female",
    phoneNumber: "(209) 726-4223",
    position: "Assistant Manager",
    department: "Accounting",
    salary: 60000,
  },
];

export default EmployeeList;